version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10-browsers
        working_directory: ~/repo
        steps:
              - checkout
              - restore_cache:
                  key: cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
              - run:
                  name: Install dependencies
                  command: yarn install --frozen-lockfile
              - save_cache:
                  key: cache-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
                  paths:
                      - ~/.cache
              - run: 
                  name: Build source code
                  command: yarn build
              - run:
                  name: Start app in background
                  command: yarn test:start-server
                  background: true
              - run:
                  name: Run E2E tests
                  command: yarn test 
                  when: on_success