version: 2
jobs:
    build:
        machine: true
        working_directory: ~/repo
        steps:
              - checkout
              - run: yarn install
              - run: yarn build
              - run:
                  name: Start app in background
                  command: yarn test:start-server
                  background: true
              - run:
                  name: Run E2E tests
                  command: yarn test 
                  when: on_success