version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10-browsers
        working_directory: ~/repo
        steps:
              - checkout
              - restore_cache:
                  key: cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
              - run:
                  name: Install dependencies
                  command: yarn install --frozen-lockfile
              - save_cache:
                  key: cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache
              - run:
                  name: Start app in background
                  command: yarn start
                  background: true
              - run:
                  name: Run E2E tests
                  command: yarn test 
                  when: on_success