version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10-browsers
        working_directory: ~/repo
        steps:
              - checkout
              - restore_cache:
                  key: {{ checksum "yarn.lock" }}
              - run: yarn install
              - save_cache:
                  key: {{ checksum "yarn.lock" }}
                  paths:
                      - node_modules/
              - run: yarn build
              - run:
                  name: Start app in background
                  command: yarn test:start-server
                  background: true
              - run:
                  name: Run E2E tests
                  command: yarn test 
                  when: on_success